name: Install
description: Install Yarn dependencies

inputs:
  cwd:
    description: "Directory containing yarn.lock"
    default: "."

runs:
  using: composite
  steps:
    # Checkout the repo
    - uses: actions/checkout@v4
      with:
        # So that we can commit from an PR triggered action
        ref: ${{ github.event.pull_request.head.ref }}

    # Install node
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: yarn
        cache-dependency-path: ${{ inputs.cwd }}/yarn.lock

    # Install Yarn deps
    - shell: bash
      run: yarn install --frozen-lockfile --cwd=${{ inputs.cwd }}
